var express = require("express");
var cors = require("cors");
var fetch = require("node-fetch");
require("dotenv").config();
var app = express();
app.use(cors());
app.use(express.json());
app.use(express.static("public"));
var JOOBLE_API_KEY = process.env.JOOBLE_API_KEY;
var PORT = process.env.PORT || 3000;
app.listen(PORT, function() { console.log("Running on port " + PORT); });
